# This is a basic workflow to help you get started with Actions

name: Deploy to github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Build Vue
        run: |
              npm ci
              npm run build
              cd dist
              git config --global user.email "benjaminkane@gmail.com"
              git config --global user.name "bkane"
              git init
              git add -A
              git commit -m 'deploy'
              git push -f https://github.com/bkane/mermimor.git master:gh-pages
        shell: bash
